name: PHPDeploy
on:
  push: 
    branches: [ master ]

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl
        ini-values: post_max_size=2000M, max_execution_time=183
    
    - run: composer --version